listen: :443

tls:
  cert: /root/fullchain.cer
  key: /root/private.key

auth:
  type: password
  password: chika

resolver:
  type: https
  https:
    addr: 1.1.1.1:443 
    timeout: 10s

acl:
  inline: 
    - reject(all, udp/443)

masquerade:
  type: proxy
  proxy:
    url: https://www.lovelive-anime.jp
    rewriteHost: true
