listen: :443

tls:
  cert: /root/fullchain.cer
  key: /root/private.key

bandwidth:
  up: 100 mbps
  down: 20 mbps

auth:
  type: password
  password: chika

resolver:
  type: https
  https:
    addr: 1.1.1.1:443
    timeout: 10s

sniff:
  enable: true 
  timeout: 2s 

acl:
  inline: 
    - reject(all, udp/443)
