listen: :443

tls:
  cert: /root/fullchain.cer
  key: /root/private.key

auth:
  type: password
  password: chika

masquerade:
  type: proxy
  proxy:
    url: https://www.lovelive-anime.jp
    rewriteHost: true
