server: 10.0.0.1

auth: chika

tls:
  sni: chika.example.com

quic:
  initStreamReceiveWindow: 16777216
  maxStreamReceiveWindow: 16777216
  initConnReceiveWindow: 33554432
  maxConnReceiveWindow: 33554432
  maxIdleTimeout: 5s
  keepAlivePeriod: 3s

bandwidth:
  up: 50 mbps
  down: 150 mbps

fastOpen: true

socks5:
  listen: 127.0.0.1:50000
