name: hysteria

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Show go env
      run: go env

    - name: git clone
      run: |
        git clone --depth 1 https://github.com/apernet/hysteria.git

    - name: go build
      run: | 
        cd hysteria
        echo 'export HY_APP_PLATFORMS="windows/amd64,linux/amd64"' >> $GITHUB_ENV
        python3 ./hyperbole.py build

    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: sing-box
        path: |
          hysteria/build/hysteria-linux-amd64
          hysteria/build/hysteria-windows-amd64.exe
